version: '3.9'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongo_ecommerce
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - mongo_data:/data/db
    networks:
      - ecommerce-network

  spring-ecommerce-backend:
    build: dockercompose
    container_name: ecommerce_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:root123@mongodb:27017/ecommerce?authSource=admin
    depends_on:
      - mongodb
    networks:
      - ecommerce-network

volumes:
  mongo_data:

networks:
  ecommerce-network:
    driver: bridge
