spring:
  application:
    name: spring-ecommerce-backend
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23lieGeI9XbN4sXr0f
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: user:email, read:user
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user