openapi: 3.0.3
info:
  title: E-Commerce Backend API
  version: 1.0.0
  description: "A minimal OpenAPI spec for a single GET endpoint returning a string."

servers:
  - url: http://localhost:8080
    description: Local Development Server

paths:
  /working:
    get:
      tags:
        - HealthCheck
      summary: Check API working status
      description: Returns a simple text message to confirm API is running.
      operationId: getWorkingStatus
      security:
        - githubOAuth2:
            - read:user
      responses:
        "200":
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example: API is working fine!
  /api/products:
    post:
      tags: [ Product ]
      summary: Create a new product
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              examples:
                ProductResponse:
                  value:
                    id: "b819364b-5b97-4d01-a273-d49a9bb95754"
                    name: "iPhone 17 Pro"
                    price: 170000.0

components:
  securitySchemes:
    githubOAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://github.com/login/oauth/authorize
          tokenUrl: https://github.com/login/oauth/access_token
          scopes:
            read:user: Read user profile data
            user:email: Access user email

  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          example: "p123"
        name:
          type: string
          example: "Wireless Mouse"
        price:
          type: number
          format: double
          example: 599.0
      required:
        - name
        - price